language: node_js
node_js:
- '7'
deploy:
  api_key:
    secure: zxPZWkoeHsrykix6HhrQo59PfBXDnrxxPanSLKNkB96SEyIDrIzry/oR5MgPao4ISoebTL7REA7D7C1/NEkz44bPU/kCpHBSb3+PAly638X17ABymM+NkR0c5jH+EsIIZ9+lPCMm9kJNimZxp9KqiM0HFerOmzWuEy6IKp92Fu8hEdzTiY5lxCnaqtC0pw2I+wfQjLuSsSLduhO7g/KgAMGK46gPwZlP3pmT9iPKkS+62iR+dWlS4d/dRXLRRAM1OCmvu0qknY7oWosBDRqwrdy65k4nEaTDy1G9i0/wBPJ5s7iaL4WK56s5WavqurhSbnH+gR2KtK2trnJ57DSt5XXSF8wkzLXHKN3I7qe0Xxh+XE4Cm9B5RtLkczReEVK9zKVbLav0PolPp8vzTBuuDr7OixnratxK3DKR5BwWGpo6wkpoJsZxiCZsr/LYZ/AQ8Hrc0A72GeML52RMAkokmwASTEnL8zgP1ab+h+2oAFxTLRcWhcusjRSKurZqsBzkLTgUgjx/IqotuNJln+Xrt5UQ6Rsi/8s6L3SKpiH28PUM474PC4k54NqEyjde0ET5KgamXOe74ZueUz1C8bLYehG3/RyxH1cTC/6rA0HWkWDjyAJLAqaYhE1CBzAVKQZERH8SoTgsIwfsiiKNXu2oEU7ojYfi2c0ogCisZQLi8RA=
